<?php
/**
 * todo: description
 *
 * @author Igor Malinovskiy <glide.name>
 * @file main.phtml
 * @date: 9/26/13
 */


$baseName = function ($path) {return basename($path);};

return <<< HTML
    <div class="page-header">
      <h1>How to contribute to Redis Desktop Manager</h1>
    </div>

    <p>We welcome your help in various areas:</p>
    <ul>
        <li><b>C++ programmers</b>, have a look at the issue <a target="_blank" rel="nofollow" href="https://github.com/uglide/RedisDesktopManager/issues">tracker</a> and start coding</li>
        <li><b>Web developers</b>, to help improve <a target="_blank" rel="nofollow" href="https://github.com/uglide/redisdesktop.com">Redis Desktop Manager site</a></li>
        <li><b>Writers</b>, to help improve the <a target="_blank" rel="nofollow"  href="https://github.com/uglide/RedisDesktopManager/wiki/Documentation">documentation</a></li>
        <li><b>Designers</b>, to create amazing logo and icons for Redis Desktop Manager</li>
    </ul>


    <div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'redisdesktop'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

HTML;

