<?php
/**
 * todo: description
 *
 * @author Igor Malinovskiy <glide.name>
 * @file main.phtml
 * @date: 9/26/13
 */


$baseName = function ($path) {return basename($path);};

return <<< HTML
    <div class="page-header">
      <h1>How to contribute to Redis Desktop Manager</h1>
    </div>

    <p>We welcome your help in various areas:</p>
    <ul>
        <li><b>C++ programmers</b>, have a look at the issue <a target="_blank" rel="nofollow" href="https://github.com/uglide/RedisDesktopManager/issues">tracker</a> and start coding</li>
        <li><b>Web developers</b>, to help improve <a target="_blank" rel="nofollow" href="https://github.com/uglide/redisdesktop.com">Redis Desktop Manager site</a></li>
        <li><b>Writers</b>, to help improve the <a target="_blank" rel="nofollow"  href="https://github.com/uglide/RedisDesktopManager/wiki/Documentation">documentation</a></li>
        <li><b>Designers</b>, to create amazing logo and icons for Redis Desktop Manager</li>
    </ul>


    <p>Have a questions? <a target="_blank" rel="nofollow" href="https://groups.google.com/forum/#!forum/redisdesktop"> Ask!</a></p>
HTML;

