<?php
/**
 * todo: description
 *
 * @author Igor Malinovskiy <glide.name>
 * @file main.phtml
 * @date: 9/26/13
 */


$baseName = function ($path) {
    return basename($path);
};

function renderUnstableBuilds($builds) {
    $html = count($builds) == 0 ? "No builds" : "";

    foreach ($builds as $build) {
        $html .= <<< HTML
<div class="row list-group-item"><a href="/builds/{$build}">{$build}</a></div>
HTML;

    }
    return $html;
}

$unstableBuilds = renderUnstableBuilds($builds);

return <<< HTML
    <div class="page-header">
      <h1>Download Redis Desktop Manager <small>version&nbsp;{$rdmData["version"]}</small></h1>
      <h4><a href="{$rdmData["url"]}">Release notes</a></h4>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3><span id="ubuntu">Ubuntu</span></h3>
                </div>
                <div class="panel-body">
                    <a class="btn btn-primary btn-large pull-right" rel="nofollow"  href="{$rdmData["download"]["ubu"]}">
                        Download package
                    </a>
                    <p><b>Supported Ubuntu versions:</b> 12.0X LTS, 13.1X, 14.0X LTS</p>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3><span id="debian">Debian</span></h3>
                </div>
                <div class="panel-body">
                    <a class="btn btn-primary btn-large pull-right" rel="nofollow"  href="{$rdmData["download"]["debi"]}">
                        Download package
                    </a>
                    <p><b>Supported Debian versions:</b> 7.5</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3><span id="windows">Windows</span></h3>
                </div>
                <div class="panel-body">
                    <a class="btn btn-primary btn-large pull-right" rel="nofollow"  href="{$rdmData["download"]["windows"]}">
                        Download Installer
                    </a>
                    <p><b>Supported Windows versions:</b>  <br /> Vista, 7, 8, 8.1 </p>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3><span id="osx">Mac OS X</span></h3>
                </div>
                <div class="panel-body">
                    <a class="btn btn-primary btn-large pull-right" rel="nofollow"  href="{$rdmData["download"]["osx"]}">
                        Download installer
                    </a>
                <p><b>Supported Mac OS X versions:</b> <br /> 10.9</p>
                </div>
            </div>
        </div>
    </div>
    <div class="panel panel-warning">
        <div class="panel-heading">
            <h3> Nightly Builds </h3> <span>These builds are for testing purposes only</span>
        </div>
        <div class="panel-body list-group">
        {$unstableBuilds}
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3> Source Code</h3>
        </div>
        <div class="panel-body">
            <a class="btn btn-success btn-large pull-right" rel="nofollow"  href="https://github.com/uglide/RedisDesktopManager">View Source</a>
            <p>
                All Source code available on GitHub
            </p>
        </div>
    </div>

HTML;
