<?php


return <<< HTML
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{$description}">
    <meta name="keywords" content="redis, gui, mac os x, windows, ubuntu, admin, panel, desktop, application">
    <meta name="author" content="Igor Malinovskiy">
    <link rel="shortcut icon" href="/css/favicon.png">

    <title>{$title}</title>

    <link href="/css/bootstrap_sl.min.css" rel="stylesheet">
    <link href="/css/style.css" rel="stylesheet">
  </head>

  <body>
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-45065665-1']);
      _gaq.push(['_setDomainName', 'redisdesktop.com']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>

    <div class="container">
      <div class="masthead">
        <ul class="nav nav-pills pull-right  site-nav-main">
          <li><a href="/community">Community</a></li>
          <!--<li><a href="http://groups.google.com/group/redisdesktop">Ask question</a></li>-->
          <li><a target="_blank" rel="nofollow" href="https://github.com/uglide/RedisDesktopManager/wiki/Documentation">Documentation</a></li>
          <li><a target="_blank" rel="nofollow" href="https://github.com/uglide/RedisDesktopManager">Project on Github</a></li>
          <li><a target="_blank" rel="nofollow" style="color: #D82C22" href="https://github.com/uglide/RedisDesktopManager/issues">Report issue</a></li>
        </ul>
        <a class="logo"  href="/">Redis Desktop Manager</a>
        <div class="clear-fix"></div>
      </div>
      {$content}
      <!-- Site footer -->
      <div class="footer">
        <p>&copy; <a href="https://twitter.com/u_glide">Igor Malinovskiy</a> - <a href="https://github.com/RedisDesktop/redisdesktop.com" rel="nofollow"><code>Improve this site</code></a> <small>last update: {$rdmData['updated']}</small></p>
        <p style="font-size: 10px; color: #cccccc"> Windows is a registered trademark of Microsoft Corporation in the United States and other countries.</p>
      </div>
    </div>
  </body>
</html>
HTML;
