<?php
/**
 * todo: description
 *
 * @author Igor Malinovskiy <glide.name>
 * @file main.phtml
 * @date: 9/26/13
 */


/**
 * @var $allContributors
 */


/**
 * @param array $users
 * @return string
 */
function renderGithubUsers(Array $users)
{
    $html = '<div class="row contributors-row">';

    $alreadyRenderedUsers = array();

    foreach ($users as $user) {
        if (!in_array($user['login'], $alreadyRenderedUsers)) {
            $alreadyRenderedUsers[] = $user['login'];
            $html .= '<a href="' .$user['html_url'] . '" target="_blank" title="' . $user['login'] . '" class="contributors-link"><img src="' . $user['avatar_url'] . '" width="75px"></a>';
        }
    }

    return $html . '</div>';
}

$links = json_encode($rdmData['download']);

/**
 * render contributors
 */
$contributorsHTML = renderGithubUsers($allContributors);

return <<< HTML
    <script src="/js/jquery.js"></script>
    <script type="text/javascript">
        $(function() {
            var links = {$links};
            var link  = '';
            var OSName = 'unknown';

            if (navigator.appVersion.indexOf('Win')!=-1) {
                OSName='Windows';
                link = links.windows;
            }

            if (navigator.appVersion.indexOf('Mac')!=-1) {
                OSName='MacOS';
                link = links.osx;
            }

            if (OSName !== 'unknown') {
                $('.more-link').css('display', 'block');
                $('.platform-name').text(' for ' + OSName);
                $('.btn-download').attr('href', link);
            }
        });
    </script>
    <div class="demo-main">
      <div class="jumbotron">
        <h1>Redis Desktop Manager</h1>
        <p class="lead">Open source GUI management tool for Redis</p>
        <p>
            <a class="btn btn-lg btn-success btn-download" href="/download">Download v.{$rdmData["version"]} <span class="platform-name"></span></a>
            <br>
            <a href="/download" class="more-link">all downloads &#x00bb;</a>
        </p>
        <h3></h3>

      </div>
    </div>

    <div class="row" id="social-buttons">
        <span>Like Redis Desktop Manager?</span>

        <iframe src="http://ghbtns.com/github-btn.html?user=uglide&repo=RedisDesktopManager&type=watch&size=large&count=true" allowtransparency="true" frameborder="0" scrolling="0" width="135" height="30"></iframe>
        <a href="https://twitter.com/share" class="twitter-share-button" data-size="large">Tweet</a>
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

        <a href="https://twitter.com/RedisDesktop" class="twitter-follow-button" data-show-count="true" data-lang="en" data-size="large" data-show-screen-name="false">Follow</a>
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

        <div class="g-plus"></div>
        <div class="g-plus" data-action="share" data-annotation="bubble" data-height="27"></div>

        <a href="https://plus.google.com/communities/118200576361490138386?prsrc=3"
           rel="publisher" target="_top" style="text-decoration:none; vertical-align: top;">
        <img src="//ssl.gstatic.com/images/icons/gplus-32.png" alt="Google+" style="border:0;width:22px;height:22px;"/>
        </a>
        <script type="text/javascript">
          (function() {
            var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
            po.src = 'https://apis.google.com/js/platform.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
          })();
        </script>

        <div class="fb-like" data-href="http://redisdesktop.com/" data-width="50" data-layout="button_count" data-action="like" data-show-faces="false" data-share="true"></div>

    </div>

    </div>

    <div class="main-demo-container" >
      <div class="container features">
          <h3>Key Features</h3>

          <div class="row">
            <div class="col-md-3 thumbnail">
                <img src="/img/features/always-at-hand.png" />
                <div class="caption">
                    <h4>Always at hand</h4>
                    Redis Desktop Manager is a GUI app available for Mac OS X, Windows, Ubuntu and Debian.
                </div>
            </div>
            <div class="col-md-3 thumbnail">
                <img src="/img/features/bigdata.png" />
                <div class="caption">
                    <h4>Works with BIG databases</h4>
                    Do you have over 1 Million keys in redis? It's not a problem.
                </div>
            </div>
            <div class="col-md-3 thumbnail">
                <img src="/img/features/ssh.png" />
                <div class="caption">
                    <h4>SSH tunnel support</h4>
                    Connect to the Redis directly or via SSH tunnel
                </div>
            </div>
            <div class="col-md-3 thumbnail">
                <img src="/img/features/clouds.png" />
                <div class="caption">
                    <h4>Clouds ready!</h4>
                   Redis Desktop Manager works with redis clouds
                </div>
            </div>
         </div>
      </div>
      </div>

    <div class="container">

      <div class="row about">
        <div class="col-lg-7">
        <h3>About</h3>

        <p>Redis Desktop Manager (aka RDM)— is a  cross-platform open source Redis DB management tool (i.e. Admin GUI). Redis Desktop Manager developed to replace a hundreds of slow and ugly tools for redis.</p>
        <p></p>
        <p>This is an early beta version of Redis Desktop Manager, that we are publishing in a hope to validate usefulness of application. We really welcome your feedback! Please submit any issues and proposals to
        <a href="https://github.com/uglide/RedisDesktopManager/issues" rel="nofollow" target="_blank">GitHub</a>. </p>

        <p>
             <a class="btn btn-success btn-download" href="/download">Download Redis Desktop Manager v.{$rdmData["version"]} <span class="platform-name"></span></a>
        </p>

        </div>
        <div class="col-lg-5">
            <a rel="nofollow" target="_blank" href="/img/features/all.png""><img class="thumbnail app-screen" src="/img/features/all.png" /></a>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12">
            <h3>Other Features</h3>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-4">
            <h4>Tree view </h4>
            View a list of all keys and switch between databases with one click.
            <img class="thumbnail" src="/img/features/tree-view.png" />
        </div>
        <div class="col-lg-4">
             <h4>Redis Console</h4>
             Run commands easily on any remote or local redis server
             <img class="thumbnail"  src="/img/features/console.png" />
        </div>
        <div class="col-lg-4">
         <h4>View key values</h4>
         View any value from chosen database.
         <img class="thumbnail"  src="/img/features/view.png" />
        </div>
      </div>
      <div class="row">
        <div class="col-lg-4">
           <h4>Local key search</h4>
           Search keys locally without adding load on Redis.
           <img class="thumbnail" src="/img/features/key-search.png" />
        </div>
        <div class="col-lg-8 more-features">
            <b>Do you need more features?</b>
            <div style="margin-top: 15px">
            <a href="https://github.com/uglide/RedisDesktopManager/issues" rel="nofollow" class="btn btn-default">Submit request</a>
            <a href="/contribute" class="btn btn-default">Contribute</a>
            <a href="https://www.bountysource.com/trackers/281529-redis-desktop-manager" target="_blank" rel="nofollow"  class="btn btn-success">Vote & Donate</a>
            </div>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-12">
            <h4>Credits</h4>
            Redis Desktop Manager would not be possible without great open-source projects:
            Redis, Qt, Qxt, libssh2, jsoncpp
        </div>
      </div>

      <div class="row" style="margin-top: 25px;" id="contributors">
        <div class="col-lg-12">
            <h4 id="contributors">Our amazing contributors</h4>
            {$contributorsHTML}
        </div>
      </div>

      <div id="fb-root"></div>
        <script>(function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/en/all.js#xfbml=1&appId=475581899219814";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>



HTML;
